log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"

# TODO нельзя на проде
api:
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  docker: {}